# plugin_generator.py
from pathlib import Path
import re
import pprint

PLUGIN_INFO = """[plugin]
name = {name}
description = {description}
license = {license}
type = speechhandler
version = 0.0.1
repo_url = {repo_url}
"""

INIT_TEMPLATE = '''# Generated by Naomi Plugin Tool
from naomi.plugin import SpeechHandlerPlugin

class {class_name}(SpeechHandlerPlugin):
    def intents(self):
        # Returned structure:
        # {{
        #   "IntentName": {{
        #       "locale": {{
        #           "en-US": {{
        #               "keywords": {{"Cat": ["a","b"]}},
        #               "templates": [self.gettext("...")]
        #           }},
        #           ...
        #       }},
        #       "action": self.handle
        #   }}
        # }}
        return {intents_src}

    def handle(self, intent, mic):
        text = intent.get('text', '')
        matches = intent.get('matches', {{}})
        if matches:
            mic.say(self.gettext("I heard matches:"))
            for k, v in matches.items():
                mic.say(f"{{k}}: " + ", ".join(v))
            return True
        if text:
            mic.say(text)
            return True
        return False
'''

README_TEMPLATE = """# {name}

{description}

This plugin was scaffolded by Naomi Plugin Tool.

- `plugin.info` contains metadata
- `__init__.py` contains the SpeechHandler with `intents()` and `handle()`
"""

def _render_templates(templates):
    # -> [self.gettext("..."), ...] (escaped)
    out = []
    for t in templates:
        esc = t.replace("\\", "\\\\").replace('"', r'\"')
        out.append(f'self.gettext("{esc}")')
    return "[" + ", ".join(out) + "]"

def _build_intents_src(intents_list):
    """
    intents_list: [ {intent_name, locales:{ code:{keywords, templates} }} ]
    """
    # Build a python-literal dict but inject code for templates and action
    intents = {}
    for intent in intents_list:
        name = intent["intent_name"]
        locmap = {}
        for code, spec in intent["locales"].items():
            locmap[code] = {
                "keywords": spec.get("keywords", {}),
                "__TEMPLATES__": _render_templates(spec.get("templates", []))
            }
        intents[name] = {
            "locale": locmap,
            "action": "self.handle"
        }

    src = pprint.pformat(intents, width=100, compact=False)
    # action: "self.handle" -> self.handle
    src = src.replace("'self.handle'", "self.handle")
    # Replace "__TEMPLATES__" placeholders
    src = re.sub(r"'__TEMPLATES__': '(\[.*?\])'",
                 lambda m: f"'templates': {m.group(1)}",
                 src, flags=re.S)
    return src

def create_plugin_skeleton(name, description, license_name, intents):
    pkg = re.sub(r"[^A-Za-z0-9_]+", "", name.replace(" ", "_")) or "plugin"
    out = Path(pkg)
    out.mkdir(parents=True, exist_ok=True)

    info_text = PLUGIN_INFO.format(
        name=name,
        description=description,
        license=license_name,
        repo_url=""
    )
    (out / "plugin.info").write_text(info_text, encoding="utf-8")

    class_name = re.sub(r"[^A-Za-z0-9]+", "", name.title()) + "Handler"
    intents_src = _build_intents_src(intents)
    (out / "__init__.py").write_text(INIT_TEMPLATE.format(class_name=class_name, intents_src=intents_src),
                                     encoding="utf-8")

    (out / "README.md").write_text(README_TEMPLATE.format(name=name, description=description), encoding="utf-8")

    return str(out.resolve())
